#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$DATAPUSHER_JOBS_USER" NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATAPUSHER_JOBS_PASSWORD';
    CREATE DATABASE "$DATAPUSHER_JOBS_DB" OWNER "$DATAPUSHER_JOBS_USER" ENCODING 'utf-8';
EOSQL
